MVCApp/MVCApp/Models/ErrorViewModel.cs
namespace MVCApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCApp/MVCApp/Models/MyViewModel.cs
namespace MVCApp.Models
{
    public class MyViewModel
    {
        public string Name { get; set; }
        public int Age { get; set; }

    }
}

MVCApp/MVCApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApp.Models;
using System.Diagnostics;

namespace MVCApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCApp/MVCApp/Controllers/MyController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApp.Models;

namespace MVCApp.Controllers
{
    public class MyController : Controller
    {
        private static List<MyViewModel> lss = new List<MyViewModel>();
        public IActionResult hello()
        {
            //MyViewModel obj1 = new MyViewModel();
            //obj1.Name = "CK";
            //obj1.Age = 10;

            return View(lss);
        }
        public IActionResult world()
        {
            return View();
        }
        public IActionResult create()
        {
            var obj_data = new MyViewModel();
            return View(obj_data);

        }
        public IActionResult submithandle(MyViewModel abcd)
        {
            lss.Add(abcd);
            //return View("hello");
            return RedirectToAction(nameof(hello));
        }
        
        
    }
}

MVCApp/MVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCApp/MVCApp/Views/My/create.cshtml
@model MVCApp.Models.MyViewModel

<h1>Create MyViewModel class objects</h1>

<form asp-controller="My" asp-action="submithandle" method="post">
  <div class="form-group">
    <label for="exampleInputEmail1" class="mb-3">Name</label>
    <input asp-for=Name type="text" class="form-control" id="exampleInputEmail1" aria-describedby="nameHelp">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1" class="mb-3">Age</label>
    <input asp-for=Age type="text" class="form-control" id="exampleInputPassword1" >
  </div>
 
  <button  type="submit" class="btn btn-primary">Submit</button>
</form>

MVCApp/MVCApp/Views/My/hello.cshtml
@model List<MVCApp.Models.MyViewModel>


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p> view from mycontroller </p>
<ul>
    @foreach (var ck in Model)
    {
        <li>@ck.Name  (@ck.Age)</li>
    }
</ul>

MVCApp/MVCApp/Views/My/world.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>world page</p>

MVCApp/MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="My" asp-action="hello">MVCApp Custom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="hello">hello</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="world">world</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="create">create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>